### ISSUE TITLE
List markdown files in a directory

### ISSUE THREAD

**Issue by nibreh** [neckcen/femto-plugin#1]
Hello

I'm glad that femto is now version 4, cool app!

How about a plugin to list all markdown files present in a content directory ? This can be use as a summary

Unfortunately, I'm not developer. If I was, I would have done !

cheers

**Comment by neckcen** [comment]
Hi nibreh, glad you enjoy femto and sorry for the late reply. I've published a directory plugin that should let you do just what you wanted. Note that if you want to list the pages for a menu or so, you can do it directly in the theme (look at default theme for an example). Have a nice day!
